/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

val nativeResourceDir = layout.projectDirectory.dir("src/main/resources/native")

val buildNative by tasks.registering {
    notCompatibleWithConfigurationCache("Uses Cargo")
    description = "Build the Rust native library and copy it into resources/native."
    doLast {
        val isJitpack = System.getenv("JITPACK") == "true"
        val os = System.getProperty("os.name").lowercase()

        // Match only the native Linux target on JitPack.
        val targets =
            if (isJitpack && os.contains("linux")) {
                listOf("x86_64-unknown-linux-gnu")
            } else {
                listOf("") // Standard local compilation
            }

        val simulationDir = File("../simulation")

        fun runCommand(vararg cmd: String) {
            val pb = ProcessBuilder(*cmd)
            pb.directory(simulationDir)
            pb.redirectErrorStream(true)
            pb.inheritIO()
            val p = pb.start()
            val code = p.waitFor()
            if (code != 0) throw GradleException("Command failed: ${cmd.joinToString(" ")} (exit $code)")
        }

        // Setup the target array cleanly
        if (isJitpack && os.contains("linux")) {
            try {
                runCommand("rustup", "target", "add", "x86_64-unknown-linux-gnu")
            } catch (e: Exception) {
                logger.warn("Failed to add Rust target: ${e.message}")
            }
        }

        targets.forEach { target ->
            val targetArgs = mutableListOf("cargo", "build", "--release")
            if (target.isNotEmpty()) {
                targetArgs.add("--target")
                targetArgs.add(target)
            }

            runCommand(*targetArgs.toTypedArray())

            val (prefix, suffix) =
                when {
                    target.contains("windows") || (target.isEmpty() && os.contains("win")) -> "" to ".dll"
                    target.contains("apple") || target.contains("darwin") || (target.isEmpty() && os.contains("mac")) -> "lib" to ".dylib"
                    else -> "lib" to ".so"
                }

            val builtLibName = "${prefix}Ouizja$suffix"
            val targetDir = if (target.isNotEmpty())
                "../${simulationDir.path}/target/$target/release"
            else
                "../${simulationDir.path}/target/release"
            val sourceFile = file("$targetDir/$builtLibName")

            if (sourceFile.exists()) {
                copy {
                    from(sourceFile)
                    into(nativeResourceDir)
                }
            } else {
                logger.warn("Could not find built library at ${sourceFile.absolutePath}")
            }
        }
    }
}
